# Generated by Django 6.0.4 on 2026-04-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_cryptoholding_cryptotransaction_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptotransaction",
            name="trade_type",
            field=models.CharField(
                choices=[("buy", "Buy"), ("sell", "Sell")], default="buy", max_length=4
            ),
        ),
    ]
